name: Cypress Test

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # install npm dependencies
      - name: Install Dependencies
        run: npm install
        # Cache the installed dependencies
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
           
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6

